### Create a new road type
POST http://localhost:3010/road-types
Content-Type: application/json

{
    "name": "Main Street",
    "roadType": "Section"
}

### Get all road types
GET http://localhost:3010/road-types
Content-Type: application/json

### Get a single road type by ID
GET http://localhost:3010/road-types/01941e2f-1b66-7438-9e36-b74a37f1711d
Content-Type: application/json

### Update a road type by ID
PUT http://localhost:3010/road-types/01941e2f-1b66-7438-9e36-b74a37f1711d
Content-Type: application/json

{
    "name": "Updated Main Street",
    "roadType": "Intersection"
}

### Delete a road type by ID
DELETE http://localhost:3010/road-types/01941e2f-590e-728b-95a3-9156ee814c45
Content-Type: application/json